### ISSUE TITLE
Runs Extra Query

### ISSUE THREAD

**Issue by chris-c-das42** [anecdotes-ai/snowflake-query#18]
Hi everyone!

Using this action results in running an extra query which returns None for the query ID and causes a downstream error in Python.

Here's my .yml for my action:

```
    steps:

      - name: Snowflake Query Action

        uses: anecdotes-ai/snowflake-query@v1.2

        id: run_queries

        with:

            snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}

            snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}

            snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}

            snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

            queries: 'ALTER GIT REPOSITORY DB_NAME.SCHEMA_NAME.REPO_STAGE_NAME FETCH;'
```

I tried adding queries such that my queries block looked something like this:

```
queries: 'USE WAREHOUSE WH_NAME;

          ALTER GIT REPOSITORY DB_NAME.SCHEMA_NAME.REPO_STAGE_NAME FETCH;'
```

And no matter the number of queries, this action is calling all queries plus one empty one at the end.

What ultimately causes the workflow to fail is the python UUID receives a None when the Snowflake-Connector-Python calls it for the final (empty) query and it returns a TypeError ```TypeError: one of the hex, bytes, bytes_le, fields, or int arguments must be given .```

Here's an example excerpt of the workflow results that queues me to the idea the action published here is calling an extra query:

```
### Running query ###
[!] Query id - REDACTED-QUERY-ID-0000-123456789
[!] Running query ### - ALTER GIT REPOSITORY DB_NAME.SCHEMA_NAME.REPO_STAGE_NAME FETCH
### Running query ###
[!] Query id - None
[!] Running query ### - 
```

If you think I've missed something or additional information is needed, let me know, thanks again for taking a look and for publishing this Action.
